###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: php-docker-mysql
      working_dir: /application
      volumes:
        - ./phpdocker/mysql:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=crypto_manager
        - MYSQL_USER=hjhj007
        - MYSQL_PASSWORD=password
      ports:
        - "3003:3306"

    webserver:
      image: nginx:alpine
      container_name: php-docker-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3001:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-docker-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

